name: drupal-training
recipe: drupal9
config:
  webroot: docroot/
services:
  appserver:
    build:
      - composer install
      - phpcs --config-set installed_paths ../../drupal/coder/coder_sniffer
